/**
 * 
 */
package br.com.database_copier.enums;

import lombok.Getter;

@Getter
public enum EvolutionTypeEnum {

	ANNOTATION("ANNOTATION", "ACOMPANHAMENTO", 1), ATTENDANCE("ATTENDANCE", "TRIAGEM", 2),
	FEEDBACK("FEEDBACK", "RETORNO REALIZADO PELO TIME CARLINK", 3), FORWARDING("FORWARDING", "ENCAMINHAMENTO", 4),
	CANCELED_FORWARDING("CANCELED_FORWARDING", "ENCAMINHAMENTO CANCELADO", 5),
	CHANGING_RESPONSIBLE("CHANGING_RESPONSIBLE", "ALTERAR RESPONSÁVEL", 6), CONCLUDED("CONCLUDED", "CASO ENCERRADO", 7),
	PROVIDER_SESSION("PROVIDER_SESSION", "SESSÃO REALIAZADA PELO PROVEDOR EXTERNO", 8),
	PROVIDER_ACCEPTED("PROVIDER_ACCEPTED", "ENCAMINHAMENTO ACEITO PELO PROVEDOR EXTERNO", 9),
	PROVIDER_REFUSED("PROVIDER_REFUSED", "ENCAMINHAMENTO RECUSADO PELO PROVEDOR EXTERNO", 10),
	PROVIDER_CONCLUDED("PROVIDER_CONCLUDED", "ENCAMINHAMENTO ENCERRADO PELO PROVEDOR EXTERNO", 11),
	SESSION("SESSION", "SESSÃO REALIZADA PELO TIME CARELINK", 12),
	MESSAGE_TO_PROVIDER("MESSAGE_TO_PROVIDER", "MENSSAGEM DO TIME CARELINK PARA O PROVEDOR EXTERNO", 13),
	PROVIDER_MESSAGE("PROVIDER_MESSAGE", "MENSSAGEM DO PROVEDOR EXTERNO PARA O TIME CARELINK", 14);

	private String id;
	private String name;
	private Integer hierarchy;

	/**
	 * 
	 * @param level
	 */
	private EvolutionTypeEnum(String id, String name, final Integer hierarchy) {
		this.id = id;
		this.name = name;
		this.hierarchy = hierarchy;
	}
}