package br.com.database_copier.entities;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import br.com.database_copier.util.GenericUtils;
import br.com.neoapp.base.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * @author generated by laucher
 */
@Data
@Entity
@Table(name = "massMessage", schema = GenericUtils.TARGET_SCHEMA)
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false, of = "id")
public class MassMessage extends BaseEntity<String> {

	private static final long serialVersionUID = 1L;

	private String id;

	@Column(columnDefinition = "VARCHAR(MAX)")
	private String descriptionHtml;

	@Column(columnDefinition = "VARCHAR(MAX)")
	private String descriptionPlainText;

	@ManyToOne
	private Channel channel;

	@ManyToOne
	private Account sender;

	private Integer patientsCount;

	private Integer responsesCount;

	@Column(updatable = false)
	private LocalDateTime createdAt;

	@Column(updatable = false)
	private String createdBy;

	private LocalDateTime updatedAt;

	private String updatedBy;

	private Boolean deleted;

	private LocalDateTime deletedAt;

	private String deletedBy;

	@Transient
	private List<Account> patients = new ArrayList<>();

	@Transient
	private String channelId;

	@Transient
	private String senderId;

}
